[package]
name = "tabss"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
crossterm = "0.27.0"
reqwest = { version = "0.11", features = ["blocking"] }
rss = { version = "2.0.6", features = ["atom"] }
tokio = { version = "1", features = ["full"] }
tui = { package = "ratatui", version = "0.22.0", features = ["all-widgets"] }
