# moccasin config
# This file may be modified by moccasin when changes are made via software,
# E.G. importing OPML files or individual feeds and changing colorschemes.

[sources]
# List URLs for Atom or RSS feeds here
feeds = [
    "https://bigthink.com/feed/all/",
    "https://feeds.feedburner.com/brainpickings/rss",
    "https://feeds.simplecast.com/dLRotFGk",
    "https://alistapart.com/main/feed/",
]

[preferences]
# The TUI color scheme, either a built-in scheme name:
#     "default" | "borland" | "darcula" | "focus" | "jungle" | "matrix" | "redshift" | "wyse"
# or a table of key-value pairs, in which value is either a hex color string,
# a built-in color string, one of:
#     | "black" | "red" | "yellow" | "blue" | "magenta" | "cyan" | "gray"
#     | "darkgray" | "lightred" | "lightgreen" | "lightyellow" | "lightblue"
#     | "lightmagenta" | "lightcyan" | "white"
# or an inline table of fg and bg colors of the same type:
#     [preferences.color_scheme]
#     name = "borland"
#     base = { fg = "#FFFFFF", bg = "#000080" }
#     overlay = { fg = "#000080", bg = "#bbbbbb" }
#     status = { fg = "#bbbbbb", bg = "#000080" }
#     border = "#bbbbbb"
#     border_active = "#FFFFFF"
#     selection = { fg = "#000080", bg = "#bbbbbb" }
#     selection_active = { fg = "#000080", bg = "#fefd72" }
#     scrollbar = { fg = "#FFFFFF", bg = "#bbbbbb" }
# All values are optional, and will inherit sensible defaults if omitted.
color_scheme = "default"

# The default sort order of feeds in the left panel, one of:
#     "a-z" | "z-a" | "newest" | "oldest" | "unread" | "custom"
# where "custom" is the order listed in [sources.feeds], and "unread" is sorted
# first by unread, then by newest.
sort_feeds = "a-z"

# Whether or not to cache feeds in a local file-backed database
cache_feeds = true

# How often to refresh feeds, in seconds.
# The default is 3600 (1 hour), and 0 means refresh is always manual.
refresh_interval = 3600

# How long to wait on a given feed before timing out, in seconds
refresh_timeout = 10
